export const SidebarService = {
  getUserData: () => {
    return {
      name: "ANDRE RIBEIRO",
      avatar: "179FOTOMARKETING.jpg",
    };
  },

  getMenuItems: () => {
    return [
      {
        id: "15",
        label: "Gestão",
        icon: "bi-gear-fill",
        subItems: [
          { label: "Perguntas Questionario", link: "/perguntas-questionario" },
          { label: "Atores", link: "/atores" },
          { label: "Vinculo Ator Instituição", link: "/vinculo-ator" },
          { label: "Questionários", link: "/questionarios" },
          { label: "Parecer Psicológico", link: "/parecer-psicologico" },
          { label: "Categoria Artefato", link: "/categoria-artefato" },
          { label: "Conteúdo História", link: "/conteudo-historia" },
          { label: "Detalhe da História", link: "/detalhe-historia" },
          { label: "Discurso", link: "/discurso" },
          { label: "Modalidade de Ensino", link: "/modalidade-ensino" },
          { label: "Natureza", link: "/natureza" },
          { label: "Profissão", link: "/profissao" },
          { label: "Tipo Vinculo", link: "/tipo-vinculo" },
          { label: "Tipo Frame", link: "/tipo-frame" },
          { label: "Instituição", link: "/unidade" },
          { label: "Artefato", link: "/artefato" },
          { label: "VINCULO COM O DI", link: "/vinculo-di" },
          { label: "Quadro Psicopedagógico", link: "/quadro-psicopedagogico" },
          { label: "consultar Profissao", link: "/consultar-profissao" },
          { label: "Trocas Comunicativas", link: "/trocas-comunicativas" },
          { label: "Grupo de Usuário", link: "/grupo-usuario" },
          { label: "consultar Tipo_Vinculo", link: "/consultar-tipo-vinculo" },
          { label: "TURNO EDUCACIONAL", link: "/turno" },
          { label: "Sessão para Família", link: "/familia-sessao" },
          { label: "Descrição das Sessões", link: "/sessao-descricao" },
          { label: "Fomulário Contexto", link: "/contexto" },
          { label: "Perguntas Contexto", link: "/perguntas-contexto" },
          { label: "Práticas ADM", link: "/praticas-adm" },
          { label: "Usuários de Acesso", link: "/usuarios" },
          { label: "Menu do Usuário", link: "/menu-usuario" },
          { label: "ANO EDUCACIONAL", link: "/ano" },
          { label: "TURMA EDUCACIONAL", link: "/turma" },
          { label: "Formulário Sub-Contexto", link: "/sub-contexto" },
          { label: "Menu do Sistema", link: "/menu" },
          { label: "Idiomas", link: "/idioma" },
        ],
      },
      {
        id: "16",
        label: "AGENDA",
        icon: "bi-calendar-week",
        subItems: [
          { label: "Agenda", link: "/agenda" },
          { label: "Horário do Psicologo", link: "/horario-psicologo" },
        ],
      },
      {
        id: "17",
        label: "Sessões",
        icon: "bi-camera-video-fill",
        subItems: [
          { label: "Gravação da Sessão", link: "/gravacao" },
          { label: "Sessão Observação", link: "/sessao-observacao" },
          { label: "Plano de Trabalho", link: "/plano-trabalho" },
          { label: "Criação de Salas", link: "/criacao-salas" },
        ],
      },
      {
        id: "18",
        label: "Cursos EAD",
        icon: "bi-pencil-fill",
        subItems: [
          { label: "Certificado Avulso", link: "/certificado" },
          { label: "Avaliação do Curso", link: "/avaliacao-curso" },
          { label: "Correção Avaliação", link: "/correcao-avaliacao" },
          { label: "Vídeo Treinamento", link: "/video-treinamento" },
          { label: "TREINAMENTO", link: "/treinamento" },
          { label: "Gestão Cursos", link: "/gestao-cursos" },
          { label: "Resposta Avaliações", link: "/resposta-avaliacoes" },
          { label: "Pergunta Avaliação", link: "/pergunta-avaliacao" },
        ],
      },
      {
        id: "19",
        label: "Avaliação",
        icon: "bi-pencil-square",
        subItems: [{ label: "Avaliação", link: "/avaliacao" }],
      },
      {
        id: "20",
        label: "Práticas",
        icon: "bi-card-heading",
        subItems: [
          { label: "Prática Profissional", link: "/pratica-profissional" },
          { label: "Prática Pedagogica", link: "/pratica-pedagogica" },
          { label: "Caderno de Atividades", link: "/caderno-atividades" },
        ],
      },
      {
        id: "21",
        label: "Indicadores",
        icon: "bi-pie-chart-fill",
        subItems: [
          { label: "Indicadores_Categoria", link: "/ind-categoria" },
          { label: "Indicadores_Contexto", link: "/ind-contexto" },
          { label: "Indicadores_Metrica", link: "/ind-metrica" },
          { label: "Indicadores_Parametro_Metrica", link: "/ind-parametro" },
          { label: "Indicadores_SubCategoria", link: "/ind-subcategoria" },
          { label: "Indicadores_SubContexto", link: "/ind-subcontexto" },
          { label: "Avaliação de Indicadores", link: "/avaliacao-indicadores" },
        ],
      },
      {
        id: "22",
        label: "Família",
        icon: "bi-people-fill",
        subItems: [
          { label: "Selecionar Sessão", link: "/selecionar-sessao" },
          { label: "Entrar como Aluno", link: "/entrar-aluno" },
        ],
      },
      {
        id: "23",
        label: "ARTEFATO",
        icon: "bi-box",
        subItems: [
          { label: "inserir Artefato", link: "/inserir-artefato" },
          { label: "Categoria Plataforma", link: "/categoria-plataforma" },
          { label: "Modalidade Artefato", link: "/modalidade-artefato" },
          { label: "Plataforma Artefato", link: "/plataforma-artefato" },
          { label: "Categoria do Artefato", link: "/categoria-do-artefato" },
          { label: "Categoria Plataforma", link: "/categoria-plataforma-grid" },
          { label: "Modalidade Artefato", link: "/modalidade-artefato-grid" },
          { label: "Idade ARTFATO", link: "/idade-artefato" },
          { label: "Importãncia Artefato", link: "/importancia-artefato" },
        ],
      },
      {
        id: "24",
        label: "IDIOMA",
        icon: "bi-globe2",
        subItems: [
          { label: "inserir Idioma", link: "/inserir-idioma" },
          { label: "consultar Idioma", link: "/consultar-idioma" },
        ],
      },
      {
        id: "25",
        label: "MENSAGENS",
        icon: "bi-envelope-fill",
        subItems: [
          { label: "MENSAGENS", link: "/mensagens" },
          { label: "AVISOS", link: "/avisos" },
        ],
      },
      {
        id: "26",
        label: "LOG GERAL",
        icon: "bi-clock-history",
        subItems: [{ label: "consultar LOG", link: "/log" }],
      },
      {
        id: "27",
        label: "Patrimônio",
        icon: "bi-shop",
        subItems: [{ label: "Registro de Patrimônio", link: "/patrimonio" }],
      },
      {
        id: "28",
        label: "RELATÓRIOS",
        icon: "bi-file-earmark-text",
        subItems: [
          { label: "Relatórios", link: "/relatorios" },
          { label: "Síntese do Parecer", link: "/sintese-parecer" },
          { label: "Histórico de Práticas", link: "/historico-praticas" },
          { label: "Evolução Histórica", link: "/evolucao-historica" },
          { label: "Síntese do Parecer PAIS", link: "/sintese-pais" },
          { label: "Acompar Teleconsulta", link: "/teleconsulta" },
          { label: "Transtorno/Déficit", link: "/transtorno" },
          { label: "Gestão dos Psicólogos", link: "/gestao-psicologos" },
          { label: "CONFERÊNCIA", link: "/conferencia" },
          { label: "Gráficos Analíticos Geral", link: "/graficos-geral" },
          { label: "Acompanhamento GERAL", link: "/acompanhamento-geral" },
          { label: "Auditoria Psicólogo", link: "/auditoria" },
          { label: "Protocolo de Atendimento", link: "/protocolo" },
        ],
      },
      {
        id: "29",
        label: "SUPORTE",
        icon: "bi-life-preserver",
        subItems: [
          { label: "Chamados", link: "/chamados" },
          { label: "Relatório de Bugs", link: "/bugs" },
        ],
      },
    ];
  },
};
