"""Schema completo e corrigido

Revision ID: 21b262adc4e0
Revises: 
Create Date: 2026-01-17 02:02:57.486411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b262adc4e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modalidade_ensino',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parecer_psicologico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profissao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Descricao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status',
    sa.Column('codigo', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('tipo_vinculo',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('unidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('NomeInstituicao', sa.String(length=255), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('logoinstituicao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('USUARIO', sa.String(length=255), nullable=True),
    sa.Column('SENHA', sa.String(length=255), nullable=True),
    sa.Column('NOME', sa.String(length=255), nullable=True),
    sa.Column('EMAIL', sa.String(length=255), nullable=True),
    sa.Column('CPF', sa.String(length=20), nullable=True),
    sa.Column('COD_EMPRESA', sa.Integer(), nullable=True),
    sa.Column('COD_STATUS', sa.Integer(), nullable=True),
    sa.Column('COD_GRUPO_USUARIO', sa.Integer(), nullable=True),
    sa.Column('COD_NIVEL', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ator',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Nome', sa.String(length=255), nullable=True),
    sa.Column('CPF', sa.String(length=20), nullable=True),
    sa.Column('Email', sa.String(length=255), nullable=True),
    sa.Column('DataNascimento', sa.Date(), nullable=True),
    sa.Column('datainiciointervencao', sa.Date(), nullable=True),
    sa.Column('ano_sessao', sa.String(length=10), nullable=True),
    sa.Column('TelefoneCel', sa.String(length=50), nullable=True),
    sa.Column('TelefoneFixo', sa.String(length=50), nullable=True),
    sa.Column('RegProfissional', sa.String(length=50), nullable=True),
    sa.Column('idiomaId', sa.Integer(), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('pais', sa.String(length=50), nullable=True),
    sa.Column('HexadecimalFoto', sa.Text(), nullable=True),
    sa.Column('unidadeId', sa.Integer(), nullable=True),
    sa.Column('profissaoId', sa.Integer(), nullable=True),
    sa.Column('ModalidadeEnsinoId', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ModalidadeEnsinoId'], ['modalidade_ensino.id'], ),
    sa.ForeignKeyConstraint(['profissaoId'], ['profissao.id'], ),
    sa.ForeignKeyConstraint(['status'], ['status.codigo'], ),
    sa.ForeignKeyConstraint(['unidadeId'], ['unidade.id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('ator_vinculo_di',
    sa.Column('atorDIId', sa.Integer(), nullable=False),
    sa.Column('atorId', sa.Integer(), nullable=False),
    sa.Column('TipoVinculoId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['TipoVinculoId'], ['tipo_vinculo.Id'], ),
    sa.ForeignKeyConstraint(['atorDIId'], ['ator.Id'], ),
    sa.ForeignKeyConstraint(['atorId'], ['ator.Id'], ),
    sa.PrimaryKeyConstraint('atorDIId', 'atorId')
    )
    op.create_table('plano_trabalho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atorDIId', sa.Integer(), nullable=True),
    sa.Column('DataInicialInteracao', sa.Date(), nullable=True),
    sa.Column('atorInteracionalId', sa.Integer(), nullable=True),
    sa.Column('atorProfessorId', sa.Integer(), nullable=True),
    sa.Column('atorPsicologoId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atorDIId'], ['ator.Id'], ),
    sa.ForeignKeyConstraint(['atorInteracionalId'], ['ator.Id'], ),
    sa.ForeignKeyConstraint(['atorProfessorId'], ['ator.Id'], ),
    sa.ForeignKeyConstraint(['atorPsicologoId'], ['ator.Id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quadro_psicopedagogico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('AtorId', sa.Integer(), nullable=True),
    sa.Column('parecerpsicologicoid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['AtorId'], ['ator.Id'], ),
    sa.ForeignKeyConstraint(['parecerpsicologicoid'], ['parecer_psicologico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessao_observacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atorid', sa.Integer(), nullable=True),
    sa.Column('DESCRICAO', sa.Text(), nullable=True),
    sa.Column('TituloSessao', sa.String(length=255), nullable=True),
    sa.Column('numerosessao', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['atorid'], ['ator.Id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessao_observacao')
    op.drop_table('quadro_psicopedagogico')
    op.drop_table('plano_trabalho')
    op.drop_table('ator_vinculo_di')
    op.drop_table('ator')
    op.drop_table('usuario1')
    op.drop_table('unidade')
    op.drop_table('tipo_vinculo')
    op.drop_table('status')
    op.drop_table('profissao')
    op.drop_table('parecer_psicologico')
    op.drop_table('modalidade_ensino')
    # ### end Alembic commands ###
