"""Migracao Completa

Revision ID: 9179ba089b16
Revises: 
Create Date: 2026-01-17 23:53:56.272061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9179ba089b16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idioma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modalidade_ensino',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parecer_psicologico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profissao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Descricao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status',
    sa.Column('codigo', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('tipo_vinculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('NomeInstituicao', sa.String(length=255), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('USUARIO', sa.String(length=255), nullable=True),
    sa.Column('SENHA', sa.String(length=255), nullable=True),
    sa.Column('NOME', sa.String(length=255), nullable=True),
    sa.Column('EMAIL', sa.String(length=255), nullable=True),
    sa.Column('CPF', sa.String(length=20), nullable=True),
    sa.Column('COD_EMPRESA', sa.Integer(), nullable=True),
    sa.Column('COD_STATUS', sa.Integer(), nullable=True),
    sa.Column('COD_GRUPO_USUARIO', sa.Integer(), nullable=True),
    sa.Column('COD_NIVEL', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ator',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('NOME', sa.String(length=255), nullable=False),
    sa.Column('DATANASCIMENTO', sa.Date(), nullable=True),
    sa.Column('DATAINICIOINTERVENCAO', sa.Date(), nullable=True),
    sa.Column('REGPROFISSIONAL', sa.String(length=100), nullable=True),
    sa.Column('EMAIL', sa.String(length=255), nullable=True),
    sa.Column('TELEFONECEL', sa.String(length=50), nullable=True),
    sa.Column('TELEFONEFIXO', sa.String(length=50), nullable=True),
    sa.Column('IDIOMAID', sa.Integer(), nullable=True),
    sa.Column('ENDERECO', sa.Text(), nullable=True),
    sa.Column('CIDADE', sa.String(length=100), nullable=True),
    sa.Column('ESTADO', sa.String(length=100), nullable=True),
    sa.Column('PAIS', sa.String(length=100), nullable=True),
    sa.Column('HEXADECIMALFOTO', sa.Text(), nullable=True),
    sa.Column('ANO_SESSAO', sa.String(length=20), nullable=True),
    sa.Column('CPF', sa.String(length=20), nullable=True),
    sa.Column('UNIDADEID', sa.Integer(), nullable=True),
    sa.Column('PROFISSAOID', sa.Integer(), nullable=True),
    sa.Column('MODALIDADEENSINOID', sa.Integer(), nullable=True),
    sa.Column('STATUS', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['MODALIDADEENSINOID'], ['modalidade_ensino.id'], ),
    sa.ForeignKeyConstraint(['PROFISSAOID'], ['profissao.id'], ),
    sa.ForeignKeyConstraint(['STATUS'], ['status.codigo'], ),
    sa.ForeignKeyConstraint(['UNIDADEID'], ['unidade.id'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('ator_vinculo_di',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ATORID', sa.Integer(), nullable=True),
    sa.Column('ATORDIID', sa.Integer(), nullable=True),
    sa.Column('TIPOVINCULOID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ATORDIID'], ['ator.ID'], ),
    sa.ForeignKeyConstraint(['ATORID'], ['ator.ID'], ),
    sa.ForeignKeyConstraint(['TIPOVINCULOID'], ['tipo_vinculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plano_trabalho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ATORDIID', sa.Integer(), nullable=True),
    sa.Column('DATAINICIALINTERACAO', sa.Date(), nullable=True),
    sa.Column('atorInteracionalId', sa.Integer(), nullable=True),
    sa.Column('atorProfessorId', sa.Integer(), nullable=True),
    sa.Column('atorPsicologoId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ATORDIID'], ['ator.ID'], ),
    sa.ForeignKeyConstraint(['atorInteracionalId'], ['ator.ID'], ),
    sa.ForeignKeyConstraint(['atorProfessorId'], ['ator.ID'], ),
    sa.ForeignKeyConstraint(['atorPsicologoId'], ['ator.ID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plano_trabalho')
    op.drop_table('ator_vinculo_di')
    op.drop_table('ator')
    op.drop_table('usuario1')
    op.drop_table('unidade')
    op.drop_table('tipo_vinculo')
    op.drop_table('status')
    op.drop_table('profissao')
    op.drop_table('parecer_psicologico')
    op.drop_table('modalidade_ensino')
    op.drop_table('idioma')
    # ### end Alembic commands ###
