"""Corrigindo models

Revision ID: bd89fd8f78f2
Revises: 
Create Date: 2026-01-17 00:06:59.073326

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd89fd8f78f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idioma')
    op.drop_table('sessao_observacao')
    op.drop_table('ator_vinculo_di')
    op.drop_table('tipo_vinculo')
    op.drop_table('plano_trabalho')
    op.drop_table('parecer_psicologico')
    op.drop_table('seg_usuario1')
    op.drop_table('quadro_psicopedagogico')
    with op.batch_alter_table('ator', schema=None) as batch_op:
        batch_op.alter_column('HEXADECIMALFOTO',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_column('IDIOMAID')
        batch_op.drop_column('DATAINICIOINTERVENCAO')
        batch_op.drop_column('ENDERECO')
        batch_op.drop_column('ESTADO')
        batch_op.drop_column('ANO_SESSAO')
        batch_op.drop_column('REGPROFISSIONAL')
        batch_op.drop_column('PAIS')
        batch_op.drop_column('CIDADE')
        batch_op.drop_column('TELEFONEFIXO')
        batch_op.drop_column('DATANASCIMENTO')

    with op.batch_alter_table('profissao', schema=None) as batch_op:
        batch_op.alter_column('Descricao',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('unidade', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=mysql.CHAR(length=2),
               type_=sa.String(length=2),
               existing_nullable=True)
        batch_op.drop_column('logoinstituicao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unidade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logoinstituicao', mysql.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('estado',
               existing_type=sa.String(length=2),
               type_=mysql.CHAR(length=2),
               existing_nullable=True)

    with op.batch_alter_table('profissao', schema=None) as batch_op:
        batch_op.alter_column('Descricao',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('ator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('DATANASCIMENTO', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('TELEFONEFIXO', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('CIDADE', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('PAIS', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('REGPROFISSIONAL', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('ANO_SESSAO', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('ESTADO', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('ENDERECO', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('DATAINICIOINTERVENCAO', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('IDIOMAID', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('HEXADECIMALFOTO',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)

    op.create_table('quadro_psicopedagogico',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('AtorId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parecerpsicologicoid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['AtorId'], ['ator.ID'], name=op.f('quadro_psicopedagogico_ibfk_1')),
    sa.ForeignKeyConstraint(['parecerpsicologicoid'], ['parecer_psicologico.id'], name=op.f('quadro_psicopedagogico_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('seg_usuario1',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('USUARIO', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('SENHA', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('COD_STATUS', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('COD_ORDENACAO', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('parecer_psicologico',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descricao', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('plano_trabalho',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ATORDIID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('DATAINICIALINTERACAO', sa.DATE(), nullable=True),
    sa.Column('atorInteracionalId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('atorProfessorId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('atorPsicologoId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ATORDIID'], ['ator.ID'], name=op.f('plano_trabalho_ibfk_1')),
    sa.ForeignKeyConstraint(['atorInteracionalId'], ['ator.ID'], name=op.f('plano_trabalho_ibfk_2')),
    sa.ForeignKeyConstraint(['atorProfessorId'], ['ator.ID'], name=op.f('plano_trabalho_ibfk_3')),
    sa.ForeignKeyConstraint(['atorPsicologoId'], ['ator.ID'], name=op.f('plano_trabalho_ibfk_4')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tipo_vinculo',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descricao', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ator_vinculo_di',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ATORID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ATORDIID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('TIPOVINCULOID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ATORDIID'], ['ator.ID'], name=op.f('ator_vinculo_di_ibfk_2')),
    sa.ForeignKeyConstraint(['ATORID'], ['ator.ID'], name=op.f('ator_vinculo_di_ibfk_1')),
    sa.ForeignKeyConstraint(['TIPOVINCULOID'], ['tipo_vinculo.id'], name=op.f('ator_vinculo_di_ibfk_3')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sessao_observacao',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('atorid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('numerosessao', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('TituloSessao', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('DESCRICAO', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['atorid'], ['ator.ID'], name=op.f('sessao_observacao_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('idioma',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descricao', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
